# 🗂️ Fake_Digits Folder Structure

This folder contains 100 fake digit images generated by the trained Generator model.

## 📁 Structure

- The digits are organized into 10 subfolders: `0`, `1`, ..., `9`.
- Each folder contains:
  - `.png` files: the generated digit image
  - `.txt` files: the corresponding latent vector used to generate the image

## 📸 Visual Examples

- Below are example views of the folder structure and file arrangement:

![Folder View 1](Fakedigits_filestructure_1.png)  
*High-level structure with digit-labeled subfolders*

![Folder View 2](Fakedigits_filestructure_2.png)  
*Detailed look into a single digit folder with paired `.png` and `.txt` files*
